FROM python:3.11-slim

WORKDIR /app

COPY streamlit_app.py .
COPY frontend/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
