version: "3.9"

services:
  db:
    image: postgres:15
    container_name: quickonboard-db
    restart: always
    environment:
      POSTGRES_DB: quickonboard
      POSTGRES_USER: onboard
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: quickonboard-redis
    ports:
      - "6379:6379"

  ollama:
    build: ./ollama
    container_name: quickonboard-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: quickonboard-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api-service

  api-service:
    build: .
    container_name: quickonboard-api
    depends_on:
      - db
      - redis
      - ollama
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: quickonboard
      DB_USER: onboard
      DB_PASS: secret123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 60s
      timeout: 5s
      retries: 3

    volumes:
      - chroma-data:/code/chroma_db

volumes:
  db-data:
  ollama-data:
  chroma-data:
